spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 910312
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.109.129
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.109.128
    port: 6379
    password: 910312
env:
  dev
