spring:
  application:
    name: oreder
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 910312
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8088
env:
  dev
